app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('home');
});


Route::group(['before' => 'auth'], function() {

	Route::resource('room', 'RoomController');
	Route::resource('booking', 'BookingController');

});

Route::get('/register', 'UserController@getRegister');
Route::post('/register', 'UserController@postRegister');

Route::get('/login', 'UserController@getLogin');
Route::post('/login', 'UserController@postLogin');

Route::get('/logout', 'UserController@getLogout');

Route::controller('password', 'RemindersController');

Route::get('/user', 'UserController@getIndex');
Route::get('/user/create',
	[
		'uses' => 'UserController@getCreate',
		'as' => 'user.create',
	]
);
Route::post('/user/create',
	[
		'uses' => 'UserController@postCreate',
		'as' => 'user.store',
	]
);
Route::get('/user/{user}/edit',
	[
		'uses' => 'UserController@getEdit',
		'as' => 'user.edit',
	]
);
Route::patch('/user/{user}/edit',
	[
		'uses' => 'UserController@patchUpdate',
		'as' => 'user.update',
	]
);
Route::delete('/user/{user}/delete',
	[
		'uses' => 'UserController@delete',
		'as' => 'user.destroy',
	]
);

app/models/Booking.php
<?php

class Booking extends Eloquent
{
	protected $fillable = array(
		'started_at', 'ended_at', 'room_id', 'name',
		'email', 'telephone', 'published'
	);

	public function room()
	{
		return $this->belongsTo('Room');
	}

}

app/controllers/BookingController.php
<?php

class BookingController extends \BaseController {

	public function index()
	{
		$bookings = Booking::all();
		return View::make('bookings.index', compact('bookings'));
	}

	public function create()
	{
		$rooms = Room::lists('name', 'id');
		return View::make('bookings.create', compact('rooms'));
	}

	public function store()
	{
		$input = Input::only(array(
			'started_at', 'ended_at', 'room_id', 'name',
			'email', 'telephone', 'published'
		));

		$rules = array(
			'started_at' => 'required|date',
			'ended_at'   => 'required|date',
			'room_id'    => 'required|exists:rooms,id',
			'name'       => 'required',
			'email'      => 'required|email',
		);

		$validation = Validator::make($input, $rules);

		if ($validation->passes()) {
			Booking::create($input);
			return Redirect::route('booking.index');
		}
		else {
			return Redirect::back()->withErrors($validation)->withInput();
		}
	}

	public function edit($id)
	{
		$booking = Booking::find($id);
		$rooms = Room::lists('name', 'id');
		return View::make('bookings.edit', compact('booking', 'rooms'));
	}

	public function update($id)
	{
		$input = Input::only(array(
			'started_at', 'ended_at', 'room_id', 'name',
			'email', 'telephone', 'published'
		));

		$booking = Booking::find($id);

		$rules = array(
			'started_at' => 'required|date',
			'ended_at'   => 'required|date',
			'room_id'    => 'required|exists:rooms,id',
			'name'       => 'required',
			'email'      => 'required|email',
		);

		$validation = Validator::make($input, $rules);

		if ($validation->passes()) {
			$booking->update($input);
			return Redirect::route('booking.index');
		}
		else {
			return Redirect::back()->withErrors($validation)->withInput();
		}
	}

	public function destroy($id)
	{
		$booking = Booking::find($id);
		$booking->delete();
		return Redirect::route('booking.index');
	}

}

app/views/bookings/create.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<h1>Add New Booking</h1>
	</div>

	{{ Form::open(array('route' => 'booking.store', 'class' => 'form-horizontal', 'files' => true)) }}
		
		<div class="form-group">
			{{ Form::label('started_at', 'Started at', array('class' => 'control-label col-sm-2')) }}
			<div class="col-xs-3">
				{{ Form::text('started_at', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('ended_at', 'Ended at', array('class' => 'control-label col-sm-2')) }}
			<div class="col-xs-3">
				{{ Form::text('ended_at', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('room_id', 'Room', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::select('room_id', $rooms, null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('name', 'Name', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::text('name', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('email', 'Email', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::email('email', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('telephone', 'Telephone', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-2">
				{{ Form::text('telephone', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-2">
				{{ Form::submit('Create New Booking', array('class' => 'btn btn-primary')) }}
			</div>
		</div>

	{{ Form::close() }}
@stop

app/views/bookings/edit.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<h1>Edit Booking</h1>
	</div>

	{{ Form::model($booking, array('route' => array('booking.update', $booking->id), 'class' => 'form-horizontal', 'method' => 'PATCH')) }}
		
		<div class="form-group">
			{{ Form::label('started_at', 'Started at', array('class' => 'control-label col-sm-2')) }}
			<div class="col-xs-3">
				{{ Form::text('started_at', $booking->started_at, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('ended_at', 'Ended at', array('class' => 'control-label col-sm-2')) }}
			<div class="col-xs-3">
				{{ Form::text('ended_at', $booking->ended_at, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('room_id', 'Room', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::select('room_id', $rooms, $booking->room_id, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('name', 'Name', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::text('name', $booking->name, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('email', 'Email', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::email('email', $booking->email, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('telephone', 'Telephone', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-2">
				{{ Form::text('telephone', $booking->telephone, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-2">
				{{ Form::submit('Update Booking', array('class' => 'btn btn-primary')) }}
			</div>
		</div>

	{{ Form::close() }}
@stop

app/views/bookings/index.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<div class="pull-right">
			<a href="{{ URL::route('booking.create') }}" class="btn btn-success">
				Add
			</a>
		</div>

		<h1>Bookings</h1>
	</div>

	<table class="table table-striped table-list">
		<thead>
			<tr>
				<th width="100">Start At</th>
				<th width="100">End At</th>
				<th wisth="140">Room</th>
				<th>Name</th>
				<th>Email</th>
				<th width="70"></th>
				<th width="100"></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($bookings as $booking)
			<tr>
				<td>{{{ $booking->started_at }}}</td>
				<td>{{{ $booking->ended_at }}}</td>
				<td>{{{ $booking->room->name }}}</td>
				<td>{{{ $booking->name }}}</td>
				<td>{{{ $booking->email }}}</td>
				<td>
					<a href="{{ URL::route('booking.edit', $booking->id) }}" class="btn btn-warning">
						Edit
					</a>
				</td>
				<td>
					{{ Form::model($booking, array('route' => array('booking.destroy', $booking->id), 'method' => 'DELETE')) }}
						{{ Form::submit('Delete', array('class' => 'btn btn-danger remove-item')) }}
					{{ Form::close() }}
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
@stop