app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('home');
});


Route::group(['before' => 'auth'], function() {

	Route::resource('room', 'RoomController');
	Route::resource('booking', 'BookingController');

});

Route::get('/register', 'UserController@getRegister');
Route::post('/register', 'UserController@postRegister');

Route::get('/login', 'UserController@getLogin');
Route::post('/login', 'UserController@postLogin');

Route::get('/logout', 'UserController@getLogout');

Route::controller('password', 'RemindersController');

Route::get('/user', 'UserController@getIndex');
Route::get('/user/create',
	[
		'uses' => 'UserController@getCreate',
		'as' => 'user.create',
	]
);
Route::post('/user/create',
	[
		'uses' => 'UserController@postCreate',
		'as' => 'user.store',
	]
);
Route::get('/user/{user}/edit',
	[
		'uses' => 'UserController@getEdit',
		'as' => 'user.edit',
	]
);
Route::patch('/user/{user}/edit',
	[
		'uses' => 'UserController@patchUpdate',
		'as' => 'user.update',
	]
);
Route::delete('/user/{user}/delete',
	[
		'uses' => 'UserController@delete',
		'as' => 'user.destroy',
	]
);

app/models/Room.php
<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class Room extends Eloquent
{
	use SoftDeletingTrait;

	protected $dates = ['deleted_at'];

	protected $fillable = array('name', 'picture');
	public $timestamps = false;

	public function bookings()
	{
		return $this->hasMany('Booking');
	}
	
}

app/controllers/RoomController.php
<?php

class RoomController extends \BaseController {

	public function index()
	{
		$rooms = Room::orderBy('name', 'asc')->get();

		return View::make('rooms.index', compact('rooms'));
	}

	public function create()
	{
		return View::make('rooms.create');
	}

	public function store()
	{
		$input = Input::only(array('name', 'picture'));
		$rules = array(
			'name'    => 'required|unique:rooms,name',
			'picture' => 'image'
		);

		$validation = Validator::make($input, $rules);

		if ($validation->passes()) {

			// do we need to upload an image?
			if (Input::hasFile('picture')) {

				// generate unique name
				$name = md5(microtime()).'.'.$input['picture']->getClientOriginalExtension();

				// upload the image using new name
				$input['picture']->move(public_path().'/images', $name);

				// change the input value
				$input['picture'] = $name;
			}

			// create the record
			Room::create($input);

			// back to index page
			return Redirect::route('room.index');
		}
		else {
			return Redirect::back()->withErrors($validation)->withInput();
		}
	}

	public function edit($id)
	{
		$room = Room::find($id);
		return View::make('rooms.edit', compact('room'));
	}

	public function update($id)
	{
		$input = Input::only(array('name', 'picture'));
		$rules = array(
			'name'    => 'required|unique:rooms,name,'.$id,
			'picture' => 'image'
		);

		$validation = Validator::make($input, $rules);

		if ($validation->passes()) {

			// get the item to modified
			$room = Room::find($id);

			// do we need to upload an image?
			if (Input::hasFile('picture')) {

				// do we have image uploded before?
				if (File::exists(public_path().'/images/'.$room->picture)) {

					// delete the file
					File::delete(public_path().'/images/'.$room->picture);
				}

				// generate unique name
				$name = md5(time()).'.'.$input['picture']->getClientOriginalExtension();

				// upload the image using new name
				$input['picture']->move(public_path().'/images', $name);

				// change the input value
				$input['picture'] = $name;
			}

			// update the record
			$room->update($input);

			// back to index page
			return Redirect::route('room.index');
		}
		else {
			return Redirect::route('room.edit', $id)->withErrors($validation)->withInput();
		}
	}

	public function destroy($id)
	{
		$room = Room::find($id);

		if ($room->bookings()->count()) {

			foreach ($room->bookings as $booking) {
				$booking->delete();
			}

		}

		$room->delete();
		return Redirect::route('room.index');
	}

}

app/views/rooms/create.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<h1>Add New Room</h1>
	</div>

	{{ Form::open(array('route' => 'room.store', 'class' => 'form-horizontal', 'files' => true)) }}
		
		<div class="form-group">
			{{ Form::label('name', 'Name', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::text('name', null, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('picture', 'Picture', array('class' => 'control-label col-sm-2')) }}

			<div class="col-sm-4">
				{{ Form::file('picture', array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-2">
				{{ Form::submit('Create New Room', array('class' => 'btn btn-primary')) }}
			</div>
		</div>

	{{ Form::close() }}
@stop

app/views/rooms/edit.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<h1>Edit Room</h1>
	</div>

	{{ Form::model($room, array('route' => array('room.update', $room->id), 'method' => 'PATCH', 'class' => 'form-horizontal', 'files' => true)) }}
		
		<div class="form-group">
			{{ Form::label('name', 'Name', array('class' => 'control-label col-sm-2')) }}
			<div class="col-sm-4">
				{{ Form::text('name', $room->name, array('class' => 'form-control')) }}
			</div>
		</div>

		<div class="form-group">
			{{ Form::label('picture', 'Picture', array('class' => 'control-label col-sm-2')) }}

			<div class="col-sm-4">
				{{ Form::file('picture', array('class' => 'form-control')) }}

				@if (! empty($room->picture))
				<hr>
				<p>Existing picture:</p>
				<div class="thumbnail">
					<img src="{{ URL::asset('images/'.$room->picture) }}">
				</div>
				@endif
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-2">
				{{ Form::submit('Update Room', array('class' => 'btn btn-primary')) }}
			</div>
		</div>

	{{ Form::close() }}
@stop

app/views/rooms/index.blade.php
@extends('master')

@section('content')

	<div class="page-header">
		<div class="pull-right">
			<a href="{{ URL::route('room.create') }}" class="btn btn-success">
				Add
			</a>
		</div>

		<h1>Rooms</h1>
	</div>

	<table class="table table-striped table-list">
		<thead>
			<tr>
				<th>Name</th>
				<th width="50">Booking</th>
                <th width="70">Room</th>
				<th width="100"></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($rooms as $room)
                <?php
                $image = '';
                if (! empty($room->picture)) {
                    $image = '<img src="'.URL::asset('images/'.$room->picture).'" width="150">';
                }
                ?>
			<tr data-content="{{{ $image }}}"
                data-html="true"
                data-trigger="hover"
                data-placement="top"
                data-toggle="popover">
				<td>{{{ $room->name }}}</td>
                <td>{{ $room->bookings()->count() }}</td>
				<td>
					<a href="{{ URL::route('room.edit', $room->id) }}" class="btn btn-warning">
						Edit
					</a>
				</td>

				<td>
					{{ Form::model($room, array('route' => array('room.destroy', $room->id), 'method' => 'DELETE')) }}
						{{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
					{{ Form::close() }}
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
@stop